### ISSUE TITLE
Implement user & permission solution

### ISSUE THREAD

**Issue by maslow** [labring/laf-roadmap#33]
## Summary

Design the use & permission solution. 

👉  **key points**:

- Use casdoor to provide registration and login capabilities
- Prefer to use user modules in sealos directly

## Intended Outcome

- User can only create allowed resource. (e.g. CreationForm)
- User can only read restricted resources:
   - resources scoped in namespace which the user owned
   - public resources in laf system namespace

## How will it work?

> TODO First study the sealos user module: the docking part with casdoor, the part of users and user groups, the part of roles and permissions, and try to consider direct reuse.

### Install Sealos User Controller

We will use the sealos user controller module directly as the permission scheme for laf.

> install user-controller in sealos environment
```shell
# install certmanager for crd webhook
sealos run labring/cert-manager:v1.8.0

# install sealos user-controller
sealos run docker.io/labring/user-controller:dev 
```

> apply the secrets required for user-controller
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
  namespace: user-system 
type: Opaque
data:
  MchID: replace_will_your_acual_key
  AppID: replace_will_your_acual_key
  MchAPIv3Key: replace_will_your_acual_key
  MchCertificateSerialNumber: replace_will_your_acual_key
  WechatPrivateKey: replace_will_your_acual_key
```

> apply a user
```yaml
apiVersion: user.sealos.io/v1
kind: User
metadata:
  name: f8699ded-58d3-432b-a9ff-56568b57a38d
spec:
  csrExpirationSeconds: 1000000000
```

### Install Sealos Auth Service & Casdoor

> TODO We have to build the cluster image for sealos auth service & casdoor since sealos community haven't provide it out-of-the-box.   @see https://github.com/labring/sealos/tree/main/service/auth

### ❔ Operations should be exposed

- user create application
- user delete application
- user update application
- user read public bundles
- user read public runtimes
- user read public regions
- user read owned applications' resources (app, oss, db, domain, stats)

### ❔ Metering & Billing

- @see #36 

## Reference
- casdoor: https://casdoor.org/
- sealos user module:  https://github.com/labring/sealos/tree/main/controllers/user
- https://github.com/labring/cluster-image/issues/148
- https://github.com/labring/sealos/tree/main/service/auth
